version: '3.4'

services:
    studentdb:
        container_name: student-app-db
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports: # not actually needed, because the two services are on the same network
            - 1433:1433
        environment:
            - ACCEPT_EULA=y
            - SA_PASSWORD=Hello@135
            - MSSQL_DB=StudentDb   # Set the database name
            - MSSQL_USER=tuan
            - MSSQL_PASSWORD=Hello@135
    studentmanagement:
        container_name: student-management-app
        image: ${DOCKER_REGISTRY-}studentmanagement
        build:
            context: .
            dockerfile: StudentManagement/Dockerfile
        ports:
            - 8001:80
        depends_on:
            - studentdb
