version: '3.4'  

networks:
    studentapp: 
 
services:
    student-sql-db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: student_sql_server2022
        ports: 
          - 1433:1433
        environment:
          - ACCEPT_EULA=y
          - SA_PASSWORD=Hello@135
          - MSSQL_DB=StudentDb   # Set the database name

        networks:
          - studentapp 
#   student-api:
#       container_name: student_api_container
#       image: tuancuchuoi/student-api:0.0.8
#       platform: linux/amd64
#       ports:
#         - 8001:80
#       build:
#           context: .
#       depends_on:
#         - student-sql-db
#       environment:
#         - DB_HOST=student-sql-db
#         - DB_NAME=StudentDb
#         - DB_SA_PASSWORD=Hello@135
#       networks:
#         - studentapp 